# Generated by Django 5.2.16 on 2026-07-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_remove_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=1234, max_length=15),
        ),
    ]
