# Generated by Django 5.2.16 on 2026-08-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
    ]
